name = "rydberg_qec"
uuid = "83f5c6ce-571b-40a2-94c2-49ce5e7b5a0f"
authors = ["Ak-ash22 14akash2000@gmail.com"]
version = "1.11.4"

[deps]
QuantumOptics         = "b9d08e2c-ec26-5004-f842-6c2ba4d0e1b8"  # Quantum optics methods
Plots                 = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"  # Plotting library
SymPy                 = "c43c736e-3764-5d55-9a28-c5c371ca6693"  # Symbolic math library
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"  # Differential equations solver
FileIO                = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"  # File input/output
SparseArrays          = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"  # Sparse matrix support
Random                = "9e28174c-4ba2-5203-b857-d8d62c4213ee"  # Random number generation
Distributed           = "8ba89e20-285c-5b6f-9357-94700520ee1b"  # Distributed computing
JLD2                  = "033835bb-276d-576a-a0d0-7875934c4c36"  # JLD2 file format
Latexify              = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"  # Latex format outputs

[compat]
QuantumOptics         = ">=0.7"
Plots                 = ">=1.20"
SymPy                 = ">=3.0"
DifferentialEquations = ">=7.0"
FileIO                = ">=1.0"
SparseArrays          = ">=1.0"
Random                = ">=1.0"
Distributed           = ">=1.0"
JLD2                  = ">=0.4"
Latexify              = ">=0.16"